title: Hayden Moore
description: Software Developer and Aspiring Researcher
- LinkedIn: https://www.linkedin.com/in/hayden-moore/
- SEI Github: https://github.com/sei-hmoore
- Email: hmmoore@andrew.cmu.edu
show_downloads: false
theme: jekyll-theme-minimal
