title: Hayden Moore
description: | 
                ## Software Developer and Aspiring Researcher from Pittsburgh, PA
                * Test1
                * Test2
show_downloads: false
theme: jekyll-theme-minimal
