title: Hayden Moore
description: Ph.D. student in Computer Science & Engineering working on neurosymbolic learning, interpretable AI, AI security, and formal verification.
show_downloads: false
theme: minima

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github, user_url: "https://github.com/HaydenMM" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=t7r6fiEAAAAJ&hl=en&oi=ao" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/hayden-moore/" }

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages: []

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .DS_Store
